name: dpkg
on: push
jobs:
  dpkg:
    runs-on: ubuntu-latest
    steps:
    - run: |
      sudo apt-get -y update
      sudo apt-get -y install \
        autoconf-archive \
        bison \
        cmake \
        dos2unix \
        flex \
        graphviz \
        iwyu
      dpkg -l
