name: dpkg
on: push
jobs:
  dpkg:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get -y update
        sudo apt-get -y install \
          autoconf-archive \
          bison \
          cmake \
          dos2unix \
          flex \
          graphviz \
          iwyu
    - name: List
      shell: bash
      run: |
        dpkg -l
