name: dpkg
on: push
jobs:
  dpkg:
    runs-on: ubuntu-latest
    steps:
    - name: test
      shell: bash
      run: |
        apt-get -y update
        apt-get -y install iwyu
        iwyu -print-resouce-dir 2>/dev/null
