name: WiX 4.0.0
on: push
jobs:
  wix_install:
    runs-on: windows-2022
    steps:
    - name: wix_install
      shell: cmd
      run: |
        dotnet tool install --global wix --version 4.0.0
        where wix
        wix --version
