name: dpkg
on: push
jobs:
  dpkg:
    runs-on: ubuntu-latest
    steps:
    - name: test
      shell: bash
      run: |
        sudo apt-cache search ^iwyu
        sudo apt-get -y update
        sudo apt-get -y install iwyu
        iwyu -print-resource-dir 2>/dev/null || true
        ls -l `iwyu -print-resource-dir 2>/dev/null || true`/include
        
